import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function LandingPage() {
  return (
    <main className="min-h-screen">
      <header className="container flex items-center justify-between py-6">
        <Link href="/" className="font-serif text-xl font-semibold">
          MuSync
        </Link>
        <nav className="flex items-center gap-3">
          <Link href="/play">
            <Button variant="ghost">Listen now</Button>
          </Link>
          <Link href="/login">
            <Button variant="ghost">Sign in</Button>
          </Link>
          <Link href="/signup">
            <Button>Get started</Button>
          </Link>
        </nav>
      </header>

      <section className="container py-24 text-center">
        <h1 className="mx-auto max-w-3xl font-serif text-5xl font-semibold leading-tight md:text-6xl">
          Background music tuned to how you focus.
        </h1>
        <p className="mx-auto mt-6 max-w-xl text-muted-foreground">
          Pick a mood and start listening. No account needed.
        </p>
        <div className="mt-10 flex justify-center gap-3">
          <Link href="/play">
            <Button size="lg">Start listening</Button>
          </Link>
          <Link href="/signup">
            <Button size="lg" variant="outline">
              Create an account
            </Button>
          </Link>
        </div>
      </section>

      <section className="container grid gap-6 py-16 md:grid-cols-3">
        {[
          {
            title: "Six moods",
            body: "Focus, calm, sleep, rainy, happy chill, night drive — each tuned for a different mode.",
          },
          {
            title: "No account needed",
            body: "Start listening instantly. Sign up only when you want custom generated tracks.",
          },
          {
            title: "AI generated",
            body: "Every track is generated by AI. Create your own with a simple prompt.",
          },
        ].map((f) => (
          <div key={f.title} className="rounded-lg border bg-card p-6 shadow-sm">
            <h3 className="font-serif text-lg font-semibold">{f.title}</h3>
            <p className="mt-2 text-sm text-muted-foreground">{f.body}</p>
          </div>
        ))}
      </section>

      <footer className="container border-t py-8 text-sm text-muted-foreground">
        &copy; MuSync
      </footer>
    </main>
  );
}
