"""feature expansion

Revision ID: 3854cd28bcd1
Revises: 8d08c9a0cc88
Create Date: 2026-04-20 20:03:21.319120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3854cd28bcd1'
down_revision: Union[str, None] = '8d08c9a0cc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True), schema='app')
    op.add_column('focus_sessions', sa.Column('total_paused_seconds', sa.Integer(), nullable=False), schema='app')
    op.add_column('focus_sessions', sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=True), schema='app')
    op.add_column('profiles', sa.Column('tos_accepted_at', sa.DateTime(timezone=True), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'tos_accepted_at', schema='app')
    op.drop_column('focus_sessions', 'abandoned_at', schema='app')
    op.drop_column('focus_sessions', 'total_paused_seconds', schema='app')
    op.drop_column('focus_sessions', 'paused_at', schema='app')
    # ### end Alembic commands ###
