"""initial schema

Revision ID: 8d08c9a0cc88
Revises: 
Create Date: 2026-04-20 14:15:42.098620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d08c9a0cc88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('preferred_mood', sa.String(), nullable=False),
    sa.Column('daily_focus_minutes', sa.Integer(), nullable=False),
    sa.Column('background_volume', sa.Integer(), nullable=False),
    sa.Column('track_limit', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('stripe_current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id'),
    schema='app'
    )
    op.create_table('seed_tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('seed_tracks_mood_idx', 'seed_tracks', ['mood'], unique=False, schema='app')
    op.create_table('focus_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['app.profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('focus_sessions_profile_id_idx', 'focus_sessions', ['profile_id'], unique=False, schema='app')
    op.create_index('focus_sessions_status_idx', 'focus_sessions', ['status'], unique=False, schema='app')
    op.create_table('playback_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('prompt_normalized', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['app.profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('playback_sessions_profile_id_idx', 'playback_sessions', ['profile_id'], unique=False, schema='app')
    op.create_table('tracks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['app.profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('tracks_is_public_published_at_idx', 'tracks', ['is_public', 'published_at'], unique=False, schema='app')
    op.create_index('tracks_mood_idx', 'tracks', ['mood'], unique=False, schema='app')
    op.create_index('tracks_profile_id_idx', 'tracks', ['profile_id'], unique=False, schema='app')
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('prompt_normalized', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('provider_job_id', sa.String(), nullable=True),
    sa.Column('ace_task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['app.profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['app.tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id'),
    schema='app'
    )
    op.create_index('generation_jobs_profile_id_idx', 'generation_jobs', ['profile_id'], unique=False, schema='app')
    op.create_index('generation_jobs_status_idx', 'generation_jobs', ['status'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('generation_jobs_status_idx', table_name='generation_jobs', schema='app')
    op.drop_index('generation_jobs_profile_id_idx', table_name='generation_jobs', schema='app')
    op.drop_table('generation_jobs', schema='app')
    op.drop_index('tracks_profile_id_idx', table_name='tracks', schema='app')
    op.drop_index('tracks_mood_idx', table_name='tracks', schema='app')
    op.drop_index('tracks_is_public_published_at_idx', table_name='tracks', schema='app')
    op.drop_table('tracks', schema='app')
    op.drop_index('playback_sessions_profile_id_idx', table_name='playback_sessions', schema='app')
    op.drop_table('playback_sessions', schema='app')
    op.drop_index('focus_sessions_status_idx', table_name='focus_sessions', schema='app')
    op.drop_index('focus_sessions_profile_id_idx', table_name='focus_sessions', schema='app')
    op.drop_table('focus_sessions', schema='app')
    op.drop_index('seed_tracks_mood_idx', table_name='seed_tracks', schema='app')
    op.drop_table('seed_tracks', schema='app')
    op.drop_table('profiles', schema='app')
    # ### end Alembic commands ###
